version: "2"
services:
  app:
    build: .
    command: "pm2-docker process.json --web"
    ports:
      - "5000:3000"
      - "9555:9615"
    depends_on:
       - mongodb
    environment:
      NODE_ENV: development
      MONGODB_HOST: mongodb
      MONGODB_DATABASE: "mbooking",
      TWILIO_API_SID: "ACe6bff8f4cd8c08bd5b088616f2c59c1f",
      TWILIO_API_TOKEN: "36fb029f5ddd847ed2b7ea641421c0a6",
    volumes:
      - /usr/src/app/node_modules

  mongodb:
    image: mongo
    ports:
      - 27057:27017
    volumes:
      - "mongodb:/data/db"
    command: --smallfiles --rest

volumes:
  mongodb:
    external:
      name: mongodb

networks:
  default:
    driver: bridge